version: 3

project:
  locator: SolaceDev_terraform-provider-solacebrokerappliance
  id: SolaceDev_terraform-provider-solacebrokerappliance
  name: terraform-provider-solacebrokerappliance
  teams: []
  labels:
    - go-dependencies
    - terraform-provider
    - EBP-Appliance

vendoredDependencies:
  forceRescans: false
  scanMethod: CLILicenseScan
  licenseScanPathFilters:
    only:
      - "**/LICENSE"
    exclude:
      - "./.git"
      - "./.github"

paths:
  exclude:
    - ./.git
    - ./.github

telemetry:
  scope: full
