name: Provider Acceptance Test

on: workflow_call


jobs:
  test:
    name: Run formal acceptance test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.22"

      - name: Check out code
        uses: actions/checkout@v4

      - name: Acceptance test
        run: |
          make testacc